---
# One command that config everything!

- hosts: localhost

  pre_tasks:
    - name: Simple echo command for recognize
      shell: echo 'Hello ' $HOSTNAME $USER
      register: command_result
    - debug: msg={{ command_result.stdout }}

  roles:
    - configuration-common
    - mac-applications
    - mac-system
